Update pwd, run script
Aiven-Open/klaw-docs pull request #142
Opened 2023-10-19 12:53 UTC by muralibasani

2023-10-19 13:30 UTC, aindriu-aiven commented on docs/HowTo/installation/run-docker.md
> +```copy-button
This is cool I need to remember this copy-button

2023-10-19 13:32 UTC, aindriu-aiven commented on docs/HowTo/installation/run-source.md
Here just mark the PW change as from version 2.6.0

2023-10-19 14:42 UTC, harshini-rangaswamy requested changes
Minor changes to the text

2023-10-19 14:42 UTC, harshini-rangaswamy commented on docs/HowTo/installation/run-source.md
> +     To pass additional configuration, pass an additional parameter like
```suggestion
     To pass additional configurations, include them as follows:
```

2023-10-19 14:42 UTC, harshini-rangaswamy commented on docs/HowTo/installation/run-docker.md
> +   - **Password:** `welcometoklaw` as of 2.6.0 Klaw release
```suggestion
   - **Password:** `welcometoklaw` (starting from the Klaw 2.6.0 release)
```

2023-10-19 14:42 UTC, harshini-rangaswamy commented on docs/HowTo/installation/run-docker.md
> +   - **Password:** `kwsuperadmin123$$` for 2.5.0 and older Klaw release
```suggestion
   - **Password:** `kwsuperadmin123$$` (for  Klaw releases 2.5.0 and older)
```

2023-10-19 14:42 UTC, harshini-rangaswamy commented on docs/HowTo/installation/run-source.md
> +   - **Password:** `kwsuperadmin123$$` for 2.5.0 and older Klaw release
```suggestion
   - **Password:** `kwsuperadmin123$$` (for  Klaw releases 2.5.0 and older)
```

2023-10-19 14:42 UTC, harshini-rangaswamy commented on docs/HowTo/installation/run-source.md
> +   - **Password:** `welcometoklaw` as of 2.6.0 Klaw release
```suggestion
   - **Password:** `welcometoklaw` (starting from the Klaw 2.6.0 release)

2023-10-19 15:27 UTC, harshini-rangaswamy approved these changes

2023-10-20 07:26 UTC, aindriu-aiven approved these changes
LGTM

2023-10-20 07:26 UTC, merged