Fix proffered username sso configuration
Aiven-Open/klaw-docs pull request #243
Opened 2024-08-02 10:23 UTC by aindriu-aiven

I have added additional information on setting up SSO with Klaw after an issue was raised recently.

2024-08-02 10:36 UTC, muralibasani requested changes
We could update klaw BE code to handle this claim internally, instead of asking user to update the claim. Ideally Klaw is dealing only with preferred usernames and not with email ids. And preferred usernames can be email ids.

IMO, this change is not required, rather we should update BE code in klaw

2024-08-02 10:36 UTC, muralibasani commented on docs/authentication-authorization/authentication/google-account.md
> +    `klaw.ad.username.attribute=email`
We should not force the organization to update this claim, as preferred_username can also be present in google SSO claims.

2024-08-02 14:46 UTC, muralibasani commented on docs/authentication-authorization/authentication/third-party-account.md
> +   Check your provider's documentation and select the attribute that defines the email address.
```suggestion
   Check your provider's documentation and select the attribute that defines the username/login name.
```

2024-08-22 10:12 UTC, muralibasani commented on docs/authentication-authorization/authentication/third-party-account.md
> +   `klaw.ad.username.attribute=preferred_username`
We can update this pr abit based on the pr https://github.com/Aiven-Open/klaw/pull/2556

2024-09-04 13:31 UTC, aindriu-aiven commented
I've overridden DCO as the unsigned commits were mine.

2024-09-04 15:11 UTC, muralibasani approved these changes

2024-09-05 06:32 UTC, merged